#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

rocker --x11 \
    --devices /dev/dri \
    --name=${DOCKER_CONTAINER_NAME} \
    --volume ${PROJECT_ROOT}/catkin_ws:/catkin_ws \
    -- ${DOCKER_IMAGE_NAME} /ros_entrypoint.sh /bin/bash
